services:
  mostro:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    volumes:
      - ./config:/config  # settings.toml and mostro.db
      - ~/.polar/networks/1/volumes/lnd:/lnd # LND data
    platform: linux/amd64
