services:
  mostro:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    volumes:
      - ./config:/config  # settings.toml and mostro.db
    platform: linux/amd64
    networks:
      - default

  nostr-relay:
    image: scsibug/nostr-rs-relay
    container_name: nostr-relay
    ports:
      - '${MOSTRO_RELAY_LOCAL_PORT:-7000}:8080'
    volumes:
      - './config/relay/data:/usr/src/app/db:Z'
      - './config/relay/config.toml:/usr/src/app/config.toml:ro,Z'

networks:
  default:
    driver: bridge
