version: '3.8'

services:
  nostr-relay:
    image: scsibug/nostr-rs-relay
    container_name: nostr-relay
    ports:
      - '${MOSTRO_RELAY_LOCAL_PORT:-7000}:8080'
    volumes:
      - './data:/usr/src/app/db:Z'
      - './config.toml:/usr/src/app/config.toml:ro,Z'

